### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by TortillasAlfred** [ngarneau/vecmap#33]
What is left to do before final submission : 
So far I have (mainly linked to myself)

- [x] Merge branches refactor and beluga_dev into master
- [x] Modify runner.py so it no longer takes num_runs arg and directly runs each experiment with the appropriate number of runs 
- [x] Write section on Grid Search (with subtask of correctly organizing the figures)
- [x] Word and coherence iteration over all the paper
- [x] Add ablation study  ~~and grid search results~~ on the additonnal languages
- [x] Make gitlab repo (and make it public)
- [ ] Mock run of results collection and plotting (We can do as if the results were all collected by dropping them all in the default mlflow_uri for the plotting and simulate results collection via toy datasets)
- [x] Have a beer (or 12)
- [x] We won't have the results for the Vocab CutOff, we will talk about this.
- [x] Remove all Beluga related stuff (including the supercomputer arg from runner and get_sbatch_rgs from Experiment)
- [x] Change x and y label axis font size (smaller)
- [x] Remove the 10⁴ in figure 2
- [x] Freeze pytgon2latex
